//FRONTEND/Staff/Login.js
import React from 'react';

const Reports = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at tincidunt mi. In sollicitudin, risus at molestie tincidunt, ligula ipsum porttitor eros, non eleifend turpis tortor eu mi. Quisque in arcu commodo, porttitor erat id, viverra nisi. Vivamus ut ante viverra, auctor massa ac, lobortis neque. Phasellus justo nisi, pharetra vel interdum eget, feugiat at felis. Vestibulum efficitur lectus non ante ultrices vulputate. Nam consequat volutpat nibh, vitae maximus velit feugiat sed. Morbi risus neque, suscipit sit amet vulputate non, iaculis sit amet nibh. Donec eleifend ipsum sed dui congue, sit amet convallis nisi sodales. In maximus imperdiet diam, eu vestibulum mauris ultricies sed. Praesent porttitor purus id luctus rhoncus.

            Pellentesque sodales odio sit amet ullamcorper dignissim. Fusce ut finibus mauris. Donec rutrum convallis purus, vitae rhoncus arcu volutpat quis. Quisque molestie scelerisque sapien. Proin sed scelerisque nunc, nec rutrum urna. Etiam eget sem ultrices, convallis nisi quis, rutrum arcu. Aenean aliquam aliquet mauris nec bibendum. Integer quis maximus diam. Nunc eu ante a eros lacinia feugiat. Aliquam aliquam mattis velit at consequat. Vestibulum eget tempor nisi. Aliquam pretium non tellus nec pellentesque. Aliquam pulvinar in nulla ac venenatis. Nunc varius nisl arcu, id ultrices diam aliquet eget. Praesent quis massa malesuada dui malesuada egestas. Sed ut ligula porta, lobortis risus sed, euismod libero.

            Donec id sapien finibus, consectetur orci eu, pellentesque velit. Sed vel massa imperdiet, sodales risus non, venenatis leo. Nullam eleifend, risus quis aliquet luctus, lacus mi imperdiet eros, vitae vulputate est orci vitae turpis. Proin vitae nisi arcu. Aenean sit amet dolor ex. Vestibulum eu purus accumsan ante pulvinar suscipit. Duis eget felis et ligula mollis viverra. Mauris at dui arcu. Nam id iaculis turpis, id vehicula risus. Nulla lobortis at velit a condimentum. Sed viverra ipsum enim, in convallis erat dictum ut. Aliquam euismod sapien sit amet purus euismod fermentum. Suspendisse potenti. Integer vel mollis nisl. Aenean pellentesque lorem quis felis semper, vel vehicula mi lacinia. Vivamus id venenatis sapien.

            Duis arcu leo, porttitor posuere imperdiet sed, vulputate sed enim. Phasellus facilisis lacinia nisi, quis scelerisque diam. Mauris velit sem, consequat bibendum neque in, commodo convallis nunc. Sed ut rhoncus ante. Nunc suscipit, libero et tempor ultrices, quam mauris elementum ante, a commodo nunc augue in arcu. Donec iaculis faucibus tortor, sed vehicula velit viverra nec. Vestibulum justo risus, ullamcorper aliquet ipsum at, dignissim porta libero. Nam interdum quis lacus non vehicula. Quisque aliquam, libero vel efficitur vehicula, eros lorem ultricies magna, et faucibus enim mi vel lacus. Integer in est tellus.

            Vestibulum nunc nisi, consequat eu lobortis et, cursus at sem. Donec maximus arcu ac nulla sodales, in hendrerit leo posuere. Praesent vel dolor mollis, fringilla mauris a, fringilla orci. Vestibulum ac ante ut felis bibendum tincidunt. Nulla id lacus iaculis, gravida neque eget, vehicula felis. Ut varius, turpis vel facilisis fermentum, leo neque consequat lorem, in facilisis enim tellus a tellus. Suspendisse volutpat cursus nunc. Fusce auctor euismod tortor scelerisque tincidunt. Mauris eget ipsum congue, condimentum magna quis, vestibulum purus. Sed vel ullamcorper ante. Sed eu imperdiet quam. Cras maximus sed felis sed laoreet. Praesent ultrices vehicula metus et convallis. Suspendisse potenti. Donec nec risus nec libero posuere malesuada.

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at tincidunt mi. In sollicitudin, risus at molestie tincidunt, ligula ipsum porttitor eros, non eleifend turpis tortor eu mi. Quisque in arcu commodo, porttitor erat id, viverra nisi. Vivamus ut ante viverra, auctor massa ac, lobortis neque. Phasellus justo nisi, pharetra vel interdum eget, feugiat at felis. Vestibulum efficitur lectus non ante ultrices vulputate. Nam consequat volutpat nibh, vitae maximus velit feugiat sed. Morbi risus neque, suscipit sit amet vulputate non, iaculis sit amet nibh. Donec eleifend ipsum sed dui congue, sit amet convallis nisi sodales. In maximus imperdiet diam, eu vestibulum mauris ultricies sed. Praesent porttitor purus id luctus rhoncus.

            Pellentesque sodales odio sit amet ullamcorper dignissim. Fusce ut finibus mauris. Donec rutrum convallis purus, vitae rhoncus arcu volutpat quis. Quisque molestie scelerisque sapien. Proin sed scelerisque nunc, nec rutrum urna. Etiam eget sem ultrices, convallis nisi quis, rutrum arcu. Aenean aliquam aliquet mauris nec bibendum. Integer quis maximus diam. Nunc eu ante a eros lacinia feugiat. Aliquam aliquam mattis velit at consequat. Vestibulum eget tempor nisi. Aliquam pretium non tellus nec pellentesque. Aliquam pulvinar in nulla ac venenatis. Nunc varius nisl arcu, id ultrices diam aliquet eget. Praesent quis massa malesuada dui malesuada egestas. Sed ut ligula porta, lobortis risus sed, euismod libero.

            Donec id sapien finibus, consectetur orci eu, pellentesque velit. Sed vel massa imperdiet, sodales risus non, venenatis leo. Nullam eleifend, risus quis aliquet luctus, lacus mi imperdiet eros, vitae vulputate est orci vitae turpis. Proin vitae nisi arcu. Aenean sit amet dolor ex. Vestibulum eu purus accumsan ante pulvinar suscipit. Duis eget felis et ligula mollis viverra. Mauris at dui arcu. Nam id iaculis turpis, id vehicula risus. Nulla lobortis at velit a condimentum. Sed viverra ipsum enim, in convallis erat dictum ut. Aliquam euismod sapien sit amet purus euismod fermentum. Suspendisse potenti. Integer vel mollis nisl. Aenean pellentesque lorem quis felis semper, vel vehicula mi lacinia. Vivamus id venenatis sapien.

            Duis arcu leo, porttitor posuere imperdiet sed, vulputate sed enim. Phasellus facilisis lacinia nisi, quis scelerisque diam. Mauris velit sem, consequat bibendum neque in, commodo convallis nunc. Sed ut rhoncus ante. Nunc suscipit, libero et tempor ultrices, quam mauris elementum ante, a commodo nunc augue in arcu. Donec iaculis faucibus tortor, sed vehicula velit viverra nec. Vestibulum justo risus, ullamcorper aliquet ipsum at, dignissim porta libero. Nam interdum quis lacus non vehicula. Quisque aliquam, libero vel efficitur vehicula, eros lorem ultricies magna, et faucibus enim mi vel lacus. Integer in est tellus.

            Vestibulum nunc nisi, consequat eu lobortis et, cursus at sem. Donec maximus arcu ac nulla sodales, in hendrerit leo posuere. Praesent vel dolor mollis, fringilla mauris a, fringilla orci. Vestibulum ac ante ut felis bibendum tincidunt. Nulla id lacus iaculis, gravida neque eget, vehicula felis. Ut varius, turpis vel facilisis fermentum, leo neque consequat lorem, in facilisis enim tellus a tellus. Suspendisse volutpat cursus nunc. Fusce auctor euismod tortor scelerisque tincidunt. Mauris eget ipsum congue, condimentum magna quis, vestibulum purus. Sed vel ullamcorper ante. Sed eu imperdiet quam. Cras maximus sed felis sed laoreet. Praesent ultrices vehicula metus et convallis. Suspendisse potenti. Donec nec risus nec libero posuere malesuada.
        </div>
    );
};

export default Reports;
